#!/usr/bin/env bash
#Write a Bash script that listens on port 98 on localhost.
#Terminal 0
#Starting my script.
#Terminal 1
#Connecting to localhost on port 98 using telnet and typing some text.

nc -1 localhost 98
